kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-b
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 80
      hostPort: 9080
    - containerPort: 443
      hostPort: 9443
networking:
  podSubnet: "10.245.0.0/16"
  serviceSubnet: "10.97.0.0/12"
